# Porta
server.port=8080

# Nome
spring.application.name=processador-consultas

# Logs detalhados do seu projeto
logging.level.com.seuprojeto=DEBUG

# Mostrar erros mais claros na resposta
server.error.include-message=always
server.error.include-binding-errors=always

# Evita cache (bom pra desenvolvimento)
spring.devtools.restart.enabled=true